# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.URLField(blank=True)),
                ('place', models.CharField(default='general', max_length=100)),
                ('description', models.TextField()),
                ('HE_Principle', models.CharField(choices=[('1', 'Visibility of System Status'), ('2', 'Match Between System and Real World'), ('3', 'User Control and Freedom'), ('4', 'Consistency and Standards'), ('5', 'Error Prevention'), ('6', 'Recognition Rather than Recall'), ('7', 'Flexibility and Efficiency of Use'), ('8', 'Aesthetic and Minimalistic Design'), ('9', 'Help Users Recognize, Diagnose, and Recover from Errors'), ('10', 'Help and Documentation')], default='1', max_length=300)),
                ('evaluators', models.ManyToManyField(related_name='project_evaluator', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
