# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 02:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='general', max_length=100)),
                ('heurPrincip', models.CharField(choices=[('1', 'Visibility of System Status'), ('2', 'Match Between System and Real World'), ('3', 'User Control and Freedom'), ('4', 'Consistency and Standards'), ('5', 'Error Prevention'), ('6', 'Recognition Rather than Recall'), ('7', 'Flexibility and Efficiency of Use'), ('8', 'Aesthetic and Minimalistic Design'), ('9', 'Help Users Recognize, Diagnose, and Recover from Errors'), ('10', 'Help and Documentation')], default='1', max_length=300)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('positivity', models.CharField(choices=[('p', 'Positive'), ('n', 'Negative')], default='n', max_length=10)),
                ('severity', models.CharField(choices=[('1', 'No problem at all'), ('2', 'Cosmetic problem'), ('3', 'Minor usability problem'), ('4', 'Major usability problem'), ('5', 'Catastrophic')], default='1', max_length=10)),
                ('frequency', models.CharField(choices=[('1', 'almost never'), ('2', 'rarely (< 10 % )'), ('3', 'occasionally (11-50 %'), ('4', 'regularly(51-89 %'), ('5', 'constantly (>90 %')], default='1', max_length=10)),
                ('Screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/%Y-%m-%d/')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Eval-Merg-Logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y-%m-%d/')),
                ('mergeUrl', models.URLField(blank=True, null=True)),
                ('exportedFile', models.FileField(blank=True, null=True, upload_to='')),
                ('evaluations', models.ManyToManyField(to='HE3.Evaluation')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Merge_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('creationTime', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(default=datetime.date(2017, 1, 29))),
                ('evaluators', models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL), related_name='project_evaluator', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listofeval',
            name='ofProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HE3.Project'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='ofProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_for_project', to='HE3.Project'),
        ),
    ]
